### ISSUE TITLE
Strange memory leak

### ISSUE THREAD

**Issue by sbragagnolo** [sbragagnolo/taskit#8] opened 2016-08-23 12:40 UTC
TKTWorker's are leaking. The only reference is weak finalizer item. 

Execute tests, and after.  

Smalltalk garbageCollect.
(TKTWorker allInstances reject: #isRunning) size > 1
Smalltalk tools pointerExplorer openOn: (TKTWorker allInstances reject: #isRunning)  first.

It happens the same with every other

**Comment by sbragagnolo** [comment] 2016-08-23 12:43
Probably is related with the fact that the worker is the executor of the finalize. Probably we are registering the worker as finalizer and not a shallow copy

**Comment by guillep** [comment] 2016-08-23 13:06
Well in my latest tests it takes time to collect, but it gets collected eventually. Because you need to give time to the gc to run and to the finalization process to execute and finalize.

Anyways, I'll test it again...

**Comment by guillep** [comment] 2016-08-23 13:12
I have no leaking workers after running the tests in latest version.

However, be careful! I changed the WorkerPool implementation in a recent commit, so the global workerpool should be reset. I am about to implement a `TKTWorkerPool>>resetGlobal` to do that.

**Comment by guillep** [comment] 2016-08-23 13:13
Santi, can you try with a new image? I'd close the issue if you cannot reproduce it with a new image from dev-0.2.

**Comment by sbragagnolo** [comment] 2016-08-23 13:35
Let me pull dev0.2 and ill do it :)

**Comment by sbragagnolo** [comment] 2016-08-23 15:11
Re checked with browser and there is no leak :)

**Closed** 2016-08-23 15:11 UTC
